remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Neel Bhandari"
description: "Industrial Automation & Robotics Portfolio"

# Optional — customize navigation (Just the Docs 2025+)
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Learning Plan"
    url: /learning-plan
  - title: "About"
    url: /about
