title: Neel Bhandari's Robotics and Automation Portfolio
remote_theme: just-the-docs/just-the-docs
color_scheme: light

logo: "Neel Bhandari's"

nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About Me"
    url: "/about"
