remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

title: "Neel Bhandari"
description: >-
  A portfolio showcasing automation & robotics projects

include_cached: false

author:
  name: "Neel Bhandari"
  avatar: "/assets/images/neel.png"  # optional
  bio: "Industrial Automation | Robotics | PLC | SCADA"
  location: "Kitchener, ON"
# Force rebuild
