title: "Neel Bhandari"
description: >-
  A professional portfolio showcasing industrial automation and robotics projects.

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

author:
  name: "Neel Bhandari"
  avatar: "/assets/images/neel.png"   # optional
  bio: "Mechanical & Automation Engineer | PLCs, Robotics, SCADA"
  location: "Kitchener, ON"

# Optional logo for nav bar
# logo: "/assets/images/logo.png"
