title: "Neel Bhandari"
description: >-
  A professional portfolio in industrial automation, robotics, and control systems.

theme: just-the-docs

# Optional settings
color_scheme: light

# Navigation structure
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Learning Plan"
    url: /learning-plan
  - title: "About"
    url: /about
