title: R-IA Portfolio by Neel Bhandari
remote_theme: just-the-docs/just-the-docs
color_scheme: light


nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About Me"
    url: "/about"
